name = "CollisionOperators"
uuid = "b58b20b1-6bfd-430a-a6d6-d2cc3899be11"
authors = ["Michael Kraus"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
