[deps]
CollisionOperators = "b58b20b1-6bfd-430a-a6d6-d2cc3899be11"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Mantis = "45fd81cf-4570-4cb4-b51d-06adeaefc15d"

[sources]
CollisionOperators = {path = ".."}

[compat]
Documenter = "1.17.0"
